version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./checkpoints:/app/checkpoints
    ports:
      - "8501:8501"
    command: streamlit run app.py
